### ISSUE TITLE
next is not a function in src/utils/catchAsync

### ISSUE THREAD

**Issue by AJONCODE** [hagopj13/node-express-mongoose-boilerplate#23]
@hagopj13  TypeError: next is not a function
    at /home/.../src/utils/catchAsync.js:2:54
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by hagopj13** [comment]
@AJONCODE I cannot reproduce your error, can you please provide more details? Which node version are you using?
I ran the app with different node versions and it worked for me in all environments (production, dev, testing).

**Comment by AJONCODE** [comment]
It happens when I have an error occurring in controller module

**Comment by AJONCODE** [comment]
It happens when I have an error occurring in controller module

**Comment by hagopj13** [comment]
@AJONCODE I still can't reproduce your error. I introduced different types of errors in one of the controllers and what I get back is always a properly formed error response, and not what you are getting.
Make sure you have installed all the dependencies.
If you are getting this error because of some changes you did in the code, kindly create a fork and do the same changes there, and I can have a look.
If you are getting this error without having done any changes, then give me a step by step guide on how to reproduce it (what type of request, to which endpoint, what are you giving as body, etc.)

**Comment by AJONCODE** [comment]
I have just created a controller 
`const registerAdmin = catchAsync(async () => {
  const user = await userService.createAdmin({
    ...config.administrator,
    referral_code: new mongoose.mongo.ObjectId(),
    account_verification: {
      is_verified: true,
    },
  });

  if (user.message === 'New administrator registered successfully') {
    // add a referrer collection for the user
    await referrerService.addReferrer({ referrer: user._id }); // no _id present
  }

  if (user.success) {
    return true;
  }
});`


Focus on comment "no _id present", the error was because of this. But catchAsync throws TypeError: next is not a function error.

**Comment by AJONCODE** [comment]
@hagopj13 Is linking active controller to a route must. I guess the error was because of this. I was using controller independent of route. I guess I should have used service instead of controller for this. Is that right?

**Comment by hagopj13** [comment]
@AJONCODE yes linking the controller to a route is a must, otherwise your controller will not get the necessary parameters (req, res, next) and hence catchAsync will not have access to next. There you have it, this is why you were getting an error.
You should use the controllers only for routes, and use services for all other things.
