### ISSUE TITLE
Add Support for debug mode

### ISSUE THREAD

**Issue by AlexYIN** [hagopj13/node-express-mongoose-boilerplate#9]
Debugging via debug | Instead of inserting and deleting console.log you can replace it with the debug function and just leave it there. You can then selectively debug portions of your code by setting DEBUG env variable. If DEBUG env variable is not set, nothing is displayed to the console.

**Comment by hagopj13** [comment]
@AlexYIN sounds like a good idea, thanks. Would you like to implement it?

**Comment by hagopj13** [comment]
@AlexYIN I was checking this issue again, and I realized that it is already possible to achieve what you are describing, with some modifications to the logger config file.
You can set the severity level of the logger in `src/config/logger.js` based on some env variables. It is now setting it to `'debug'` when running in development mode, and to `'info'` otherwise. You can of course change this to check for DEBUG env varibale and set it accordingly. You can check winston documentation for more details on this https://github.com/winstonjs/winston#logging-levels.
After this, you can use the logger.debug method anywhere, as follow:
```javascript
const logger = require('<path to src>/config/logger');

// this will be logged only when debug is enabled
logger.debug('message');
```
